"""таблица gko_data

Revision ID: e066b82380f0
Revises: b31f874c1516
Create Date: 2023-10-11 14:11:36.062647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e066b82380f0'
down_revision: Union[str, None] = 'b31f874c1516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gko_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kn', sa.String(length=20), nullable=False),
    sa.Column('kc', sa.Float(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('doc_num', sa.String(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('doc_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('date_time', sa.Date(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('date_found', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_placement', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gko_data')
    # ### end Alembic commands ###
